### ISSUE TITLE
[Android] FacebookLoginPackage cannot be applied to given types

### ISSUE THREAD

**Issue by Sexycrets** [magus/react-native-facebook-login#82]
Using version 1.0.2 it used to work just fine, now I upgraded to react-native 0.20 (not sure if that is the cause) but on iOS all works well on Android I now get this error:

```
/MainActivity.java:41: error: constructor FacebookLoginPackage in class FacebookLoginPackage cannot be applied to given types;
        mFacebookLoginPackage = new FacebookLoginPackage(this);
                                ^
  required: no arguments
  found: MainActivity
  reason: actual and formal argument lists differ in length
/[...]/MainActivity.java:112: error: cannot find symbol
        mFacebookLoginPackage.handleActivityResult(requestCode, resultCode, data);
                             ^
  symbol:   method handleActivityResult(int,int,Intent)
  location: variable mFacebookLoginPackage of type FacebookLoginPackage
2 errors
:app:compileDebugJavaWithJavac FAILED
```

I don't know if to update to the latest version of this package since I haven't updated the react-native templates when I updated to 0.20 so your documentation might not apply. What do you suggest?

**Comment by pedro** [comment]
Ran into the same issue – turns out the Android setup has been simplified, which is great. Delete `mFacebookLoginPackage` and follow the simpler setup specified here:

https://github.com/magus/react-native-facebook-login/blob/master/android/README.md

**Comment by nabn** [comment]
That's what I ended up doing. I had to go the extra mile of deleting the android folder again, running `react-native android`, and setting up all the manually installed packages again.

**Comment by lwhiteley** [comment]
so this is resolved then :+1:

**Comment by fenderrex** [comment]
> Ran into the same issue – turns out the Android setup has been simplified, which is great. Delete mFacebookLoginPackage and follow the simpler setup specified here:
> 
> https://github.com/magus/react-native-facebook-login/blob/master/android/README.md
i tried npm remove mFacebookLoginPackage  but npm does not see it.
i ran rnpm remove mFacebookLoginPackage returns you guessed it a blank line
rnpm uninstall mFacebookLoginPackage seeemed to do something
 so i ran react-native run-android and its not failing to import it... I can not find it in my node_modules folder...
should i not expect this error

` new FacebookLoginPackage(this); `
to change into a import error?

sorry for the node noob question :)
